version: '3.8'

services:

  nextt-service:
    build:
      context: ./
      dockerfile: ./Dockerfile-dev
    container_name: nextt-container
    volumes:
      - ./:/usr/src/app
    ports:
      - '3000:3000'
    stdin_open: true
