version: '3.8'

services:

  next-service:
    build:
      context: ./
      dockerfile: ./Dockerfile-dev
    container_name: next-container
    volumes:
      - ./:/usr/src/app
    ports:
      - '3000:3000'
    stdin_open: true
